# Generated by Django 2.2.7 on 2019-11-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='on_market',
            field=models.BooleanField(default=False),
        ),
    ]
