# Generated by Django 2.2.7 on 2019-11-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_on_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectjob',
            name='due',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projectjob',
            name='start',
            field=models.DateField(),
        ),
    ]
