# Generated by Django 2.2.7 on 2019-11-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectjob',
            name='due',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='projectjob',
            name='start',
            field=models.TimeField(),
        ),
    ]
