# Generated by Django 2.2.7 on 2019-11-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20191124_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectjob',
            name='due',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projectjob',
            name='start',
            field=models.DateField(),
        ),
    ]
