# Generated by Django 2.2.7 on 2019-12-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20191124_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectjob',
            name='isFinished',
            field=models.BooleanField(default=False),
        ),
    ]
