# Generated by Django 2.2.7 on 2019-12-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectjob_howlate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectjob',
            name='howLate',
            field=models.IntegerField(default=0),
        ),
    ]
