# Generated by Django 2.2.7 on 2019-12-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20191212_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectjob',
            name='howLate',
            field=models.DateField(),
        ),
    ]
