# Generated by Django 2.2.7 on 2019-12-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20191218_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectjob',
            name='howLate',
            field=models.FloatField(),
        ),
    ]
