# Generated by Django 2.2.7 on 2019-12-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_projectjob_onduty'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectjob',
            name='charger_true',
            field=models.BooleanField(default=False),
        ),
    ]
