# Generated by Django 2.2.7 on 2019-12-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_projectjob_charger_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectjob',
            name='importance',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
