# Generated by Django 2.2.7 on 2019-12-19 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0016_projectjob_importance'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('inCharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_contribution', to=settings.AUTH_USER_MODEL)),
                ('inProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_contribution', to='projects.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
