# Generated by Django 2.2.7 on 2019-12-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_jobcontribution_inprojectjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcontribution',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
