# Generated by Django 2.2.7 on 2019-12-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_jobcontribution_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectjob',
            name='howLate',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
