# Generated by Django 2.2.7 on 2019-11-27 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applyto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='applyto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applyto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apply',
            name='apply_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
